# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `jsbundling-rails` gem.
# Please instead update this file by running `bin/tapioca gem jsbundling-rails`.


# source://jsbundling-rails//lib/jsbundling-rails.rb#1
module Jsbundling; end

# source://jsbundling-rails//lib/jsbundling/engine.rb#2
class Jsbundling::Engine < ::Rails::Engine
  class << self
    private

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr___callbacks; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr___callbacks=(new_value); end
  end
end

# source://jsbundling-rails//lib/jsbundling/version.rb#2
Jsbundling::VERSION = T.let(T.unsafe(nil), String)
