# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Inputs::OrderingInput`.
# Please instead update this file by running `bin/tapioca dsl Inputs::OrderingInput`.


class Inputs::OrderingInput
  sig { returns(::SortDirection) }
  def direction; end

  sig { returns(::String) }
  def order_on_uid; end
end
