# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Inputs::TableSourceInput`.
# Please instead update this file by running `bin/tapioca dsl Inputs::TableSourceInput`.


class Inputs::TableSourceInput
  sig { returns(T.nilable(::String)) }
  def list_uid; end

  sig { returns(::String) }
  def row_type; end
end
