query GetTableDefinition($source: TableSourceInput!) {
  tableDefinition(source: $source) {
    ...TableDefinition
  }
}

fragment TableDefinition on TableDefinition {
  id
  columns {
    ...ColumnDefinition
  }
}

fragment ColumnDefinition on Column {
  id
  name
}
